(library
 (name google_api_pubsub)
 (public_name google-api-pubsub)
 (libraries google-api google-api.runtime uri yojson))

(rule
 (targets google_api_pubsub.ml.gen google_api_pubsub.mli.gen)
 (deps
  (:discovery %{project_root}/discovery/pubsub.v1.json))
 (action
  (run %{exe:../../gen/main.exe} %{discovery} %{targets})))

(rule
 (alias runtest)
 (action
  (diff google_api_pubsub.ml google_api_pubsub.ml.gen)))

(rule
 (alias runtest)
 (action
  (diff google_api_pubsub.mli google_api_pubsub.mli.gen)))
